title: Kristen Healy
description: Porfolio
theme: jekyll-theme-dinky
logo: /assets/images/Kristen_circle_150.png
description: > # sidebar
  <a href="https://www.linkedin.com/in/kristenhealy">LinkedIn</a>
