theme: jekyll-theme-dinky
logo: /assets/images/Kristen_circle_150.png
title: Kristen Healy
description: 
 <a href="https://khealy.github.io">Portfolio Home</a><br/>
 <a href="https://www.linkedin.com/in/kristenhealy">LinkedIn</a>
